### ISSUE TITLE
Compensate for leading slash in API URL inserted by grafana_api

### ISSUE THREAD

**Issue by amotl** [daq-tools/grafana-wtf#4]
@jangaraj just reported through https://github.com/daq-tools/grafana-wtf/issues/2#issuecomment-490346459:
> According to doc user needs to use `export GRAFANA_URL=https://daq.example.org/grafana/`. But that trailing slash is a problem in my case (I use https://domain.org/). Could you handle that in the code, so user will be able to use URL with/without trailing slash, please?

Thanks!

**Comment by amotl** [comment]
@jangaraj: Would you share an excerpt of your output when running
```
grafana-wtf find foobar --cache-ttl=inf --debug --http-logging
```
after upgrading to the most recent version?

---

I am asking because stripping the trailing slash would not work for us and croak like that
```
2019-05-08 07:56:07,419 [urllib3.connectionpool] DEBUG  : Starting new HTTPS connection (1): weather.hiveeyes.org:443
2019-05-08 07:56:07,583 [urllib3.connectionpool] DEBUG  : https://weather.hiveeyes.org:443 "GET //grafana6api/datasources HTTP/1.1" 404 None
2019-05-08 07:56:07,584 [grafana_wtf.core      ] ERROR  : GrafanaClientError: Client Error 404: <html>
<head><title>404 Not Found</title></head>
<body bgcolor="white">
<center><h1>404 Not Found</h1></center>
<hr><center>nginx/1.10.3</center>
</body>
</html>
```

Nevertheless I am seeing a double slash at the **beginning** of the URL:`GET //grafana6` here. Maybe **this** is responsible for bailing out on your side?

**Comment by jangaraj** [comment]
```
2019-05-08 07:02:14,326 [grafana_wtf.core      ] INFO   : Scanning dashboards
2019-05-08 07:02:14,537 [urllib3.connectionpool] DEBUG  : https://domain.com:443 "GET //api/search?limit=5000 HTTP/1.1" 404 None
```
So invalid ULR has been generated:
```
https://domain.com:443//api/search?limit=5000
```
Correct URL:
```
https://domain.com:443/api/search?limit=5000
```

**Comment by amotl** [comment]
Thanks for sharing that, I just wanted to make sure we are talking about the same thing.

As far as I can see, there's an additional slash being inserted after the hostname, which is **straight in the midst** of the variable obtained from `--grafana-url` or `GRAFANA_URL`.

We will try to find the place where this single forward slash gets inserted erroneously.

**Comment by amotl** [comment]
As the URL pattern used for constructing the full API resource URL by [grafana_api](https://github.com/m0nhawk/grafana_api) looks like [1]
```
url_pattern = '{protocol}://{host}/{url_path_prefix}api'
```
we figure `url_path_prefix` is expected to be obtained without the **leading** slash. So, the code should account for that appropriately.

[1] https://github.com/m0nhawk/grafana_api/blob/v0.5.2/grafana_api/grafana_api.py#L64-L68

**Comment by amotl** [comment]
`grafana-wtf-0.8.1` should mitigate the double slash problem you have been reporting, @jangaraj. Thanks again and happy Grafana searching.
